service: RealEstate
disabledDeprecations: "*" # To disable all deprecation messages

provider:
  name: aws
  profile: real_estate
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${file(./config/config.${opt:stage, self:provider.dev, 'dev'}.json):REGION}
  environment:
    ENV: ${opt:stage, 'dev'}
    USER_POOL_ID: ${file(./config/config.${opt:stage, self:provider.dev, 'dev'}.json):USER_POOL_ID}
    REGION: ${file(./config/config.${opt:stage, self:provider.dev, 'dev'}.json):REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendRawEmail
        - dynamodb:*
      Resource: "*"

functions:
  # authorize:
  #   handler: handler.authorize

  sendRecieverEmail:
    handler: handler.sendRecieverEmail
    events:
      - http:
          path: api/sendRecieverEmail
          method: post
          cors: true

  putUsersInDB:
    handler: handler.putUsersInDB
    events:
      - http:
          path: api/putUsersInDB
          method: post
          cors: true

  userFloors:
    handler: handler.userFloors
    events:
      - http:
          path: api/userFloors
          method: post
          cors: true

  userRooms:
    handler: handler.userRooms
    events:
      - http:
          path: api/userRooms
          method: post
          cors: true

  userDetail:
    handler: handler.userDetail
    events:
      - http:
          path: api/userDetail
          method: post
          cors: true

  userExterior:
    handler: handler.userExterior
    events:
      - http:
          path: api/userExterior
          method: post
          cors: true
